name: Auto-merge PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'ArtemBReal' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Development PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    autoGenerateLog:
      steps:
      # Использование действия checkout для клонирования репозитория  
        - uses: actions/checkout@v2  
      # Выкачивание всей истории коммитов, необходимо для корректной работы многих инструментов генерации changelog
          with:
            fetch-depth: 0  
   
        - name: Download and Install git-cliff
          run: |  
            curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz 
            tar -xzf git-cliff.tar.gz  
            mv git-cliff-2.2.1/git-cliff /usr/local/bin/ 
    # Шаг для генерации файла CHANGELOG.md
        - name: Generate Changelog
      # Запуск git-cliff с указанием конфигурационного файла и выходного файла
          run: git-cliff --config cliff.toml --output CHANGELOG.md  
     
    # Шаг для коммита изменений
        - name: Commit Changelog
      # Команды для выполнения  
          run: |  
            git config --global user.name 'Artem Borisov'
            git config --global user.email artemb.ggw@gmail.com
            git add CHANGELOG.md
            git commit -m "Обновление CHANGELOG.md"
            git push https://github.com/${{ github.repository }}.git HEAD:main  
